name: online_groceries
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fl_country_code_picker: ^0.1.5
  flutter_rating_bar: ^4.0.1
  get: ^4.6.5
  http: ^1.1.0
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  flutter_timezone: ^1.0.6
  flutter_easyloading: ^3.0.5
  cached_network_image: ^3.2.3

dependency_overrides:
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/img/a_about.png
    - assets/img/a_delivery_address.png
    - assets/img/a_help.png
    - assets/img/a_my_detail.png
    - assets/img/a_order.png
    - assets/img/a_promocode.png
    - assets/img/account_tab.png
    - assets/img/add.png
    - assets/img/add_green.png
    - assets/img/app_logo.png
    - assets/img/apple.png
    - assets/img/apple_red.png
    - assets/img/back.png
    - assets/img/bakery_snacks.png
    - assets/img/banana.png
    - assets/img/banner_top.png
    - assets/img/beef_bone.png
    - assets/img/beverages.png
    - assets/img/bottom_bg.png
    - assets/img/broiler_chicken.png
    - assets/img/cart_tab.png
    - assets/img/checkbox.png
    - assets/img/checkbox_check.png
    - assets/img/close.png
    - assets/img/cocacola_can.png
    - assets/img/color_logo.png
    - assets/img/cooking_oil.png
    - assets/img/dairy_eggs.png
    - assets/img/detail_open.png
    - assets/img/diet_coke.png
    - assets/img/google_logo.png
    - assets/img/juice_apple_grape.png
    - assets/img/lettuce.png
    - assets/img/location.png
    - assets/img/logout.png
    - assets/img/master.png
    - assets/img/meat_fish.png
    - assets/img/next.png
    - assets/img/order_fail.png
    - assets/img/orenge_juice.png
    - assets/img/paymenth_methods.png
    - assets/img/pepper.png
    - assets/img/pepsi_can.png
    - assets/img/pulses.png
    - assets/img/rice.png
    - assets/img/search.png
    - assets/img/select_location.png
    - assets/img/share.png
    - assets/img/sign_in_top.png
    - assets/img/splash_logo.png
    - assets/img/sprite_can.png
    - assets/img/store_tab.png
    - assets/img/subtack.png
    - assets/img/t_close.png
    - assets/img/u1.png
    - assets/img/u2.png
    - assets/img/welcom_bg.png
    - assets/img/your_banner_image.png

  fonts:
    - family: HKGrotesk
      fonts:
        - asset: assets/font/HKGrotesk-Regular.otf
        - asset: assets/font/HKGrotesk-Bold.otf
          weight: 700
    - family: Gilroy
      fonts:
        - asset: assets/font/Gilroy-Regular.ttf
        - asset: assets/font/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/font/Gilroy-SemiBold.ttf
          weight: 600
        - asset: assets/font/Gilroy-Bold.ttf
          weight: 700
    - family: Airbnb Cereald
      fonts:
        - asset: assets/font/Airbnb-Cereald-Medium.otf
    - family: Sveningsson
      fonts:
        - asset: assets/font/Sveningsson.ttf
